### ISSUE TITLE
ServerTestCase not running on Windows

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya-testsuite#34]
### What steps will reproduce the problem?
Install and use test suite (ServerTestCase) on Windows.

### What is the expected result?
Tests will run as expected

### What do you get instead? (A Screenshot can help us a lot!)
Errors / not running

### Additional infos
I think it's comming from `createServer()` and `killServer()` and that they should have operating system check and adjust the command. So it should be something similar to the following I think:

(Still missing something, so not the solution and no pr...)
```
protected function createServer($host, $port, $documentRoot)
{
    if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
        $command = sprintf(PHP_BINARY . ' -S %s:%d -t %s >NUL 2>&1 &  ......(Tasklist?).......', $host, $port, $documentRoot);
    } else {
        $command = sprintf(PHP_BINARY . ' -S %s:%d -t %s >/dev/null 2>&1 & echo $!', $host, $port, $documentRoot);
    }
    $output = [];
    exec($command, $output);
    return (int) $output[0];
}
```
and
```
protected function killServer($pid)
{
    if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
        exec('taskkill /pid ' . (int) $pid);
    } else {
        exec('kill -9 ' . (int) $pid);
    }
}
```

| Q                | A
| ---------------- | ---
| LUYA Version     |  1.2.1
| LUYA Testsuite |  1.0.30
| PHP Version      | 7.4
| Platform         | WAMP
| Operating system | Windows

**Comment by nadar** [comment]
Yes indeed, wont work on windows. A PR would be nice! 👍

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.

**Comment by nadar** [comment]
@JohnnyMcWeed a PR would still be very nice :-)
